export const COLORS = {
  light: {
    background: '#FAFAFA',
    foreground: '#0A0A0A',
    card: '#F0F0F0',
    cardForeground: '#0A0A0A',
    popover: '#F0F0F0',
    popoverForeground: '#0A0A0A',
    primary: '#BAFF29',
    primaryForeground: '#0A0A0A',
    secondary: '#E8E8E8',
    secondaryForeground: '#0A0A0A',
    muted: '#E0E0E0',
    mutedForeground: 'rgba(10, 10, 10, 0.5)',
    accent: '#E8E8E8',
    accentForeground: '#0A0A0A',
    destructive: '#FF2E63',
    destructiveForeground: '#FAFAFA',
    info: '#00D4FF',
    infoForeground: '#0A0A0A',
    surface: '#E8E8E8',
    surfaceForeground: '#0A0A0A',
    border: 'rgba(10, 10, 10, 0.15)',
    input: 'rgba(10, 10, 10, 0.15)',
    ring: '#BAFF29',
  },
  dark: {
    background: '#0A0A0A',
    foreground: '#FAFAFA',
    card: '#111111',
    cardForeground: '#FAFAFA',
    popover: '#111111',
    popoverForeground: '#FAFAFA',
    primary: '#BAFF29',
    primaryForeground: '#0A0A0A',
    secondary: '#1A1A1A',
    secondaryForeground: '#FAFAFA',
    muted: '#1A1A1A',
    mutedForeground: 'rgba(250, 250, 250, 0.5)',
    accent: '#1A1A1A',
    accentForeground: '#FAFAFA',
    destructive: '#FF2E63',
    destructiveForeground: '#0A0A0A',
    info: '#00D4FF',
    infoForeground: '#0A0A0A',
    surface: '#161616',
    surfaceForeground: '#FAFAFA',
    border: 'rgba(250, 250, 250, 0.1)',
    input: 'rgba(250, 250, 250, 0.1)',
    ring: '#BAFF29',
  },
} as const;

export const NAV_THEME = {
  light: {
    background: COLORS.light.background,
    border: COLORS.light.border,
    card: COLORS.light.card,
    notification: COLORS.light.destructive,
    primary: COLORS.light.primary,
    text: COLORS.light.foreground,
  },
  dark: {
    background: COLORS.dark.background,
    border: COLORS.dark.border,
    card: COLORS.dark.card,
    notification: COLORS.dark.destructive,
    primary: COLORS.dark.primary,
    text: COLORS.dark.foreground,
  },
} as const;

export const HEX_COLORS = {
  black: '#0A0A0A',
  white: '#FAFAFA',
  pink: '#FF2E63',
  green: '#BAFF29',
  blue: '#00D4FF',
  primary: '#BAFF29',
  destructive: '#FF2E63',
  info: '#00D4FF',
  muted: '#1A1A1A',
  mutedForeground: 'rgba(250, 250, 250, 0.5)',
  border: 'rgba(250, 250, 250, 0.1)',
  background: '#0A0A0A',
  foreground: '#FAFAFA',
} as const;

export const NATIVE_SLIDER = {
  minimumTrackTintColor: HEX_COLORS.green,
  maximumTrackTintColor: HEX_COLORS.border,
  thumbTintColor: HEX_COLORS.green,
} as const;
